# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-22 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=10)),
                ('latitude', models.CharField(max_length=10)),
                ('longitude', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('email', models.CharField(max_length=50)),
                ('phoneNum', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='polygon',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crudapp.Provider'),
        ),
    ]
